name: test_ui_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  # UI & Icons
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  cached_network_image: ^3.4.1
  
  # State Management
  provider: ^6.1.1
  
  # Storage
  shared_preferences: ^2.2.2
  share_plus: ^12.0.0
  
  # Network
  http: ^1.1.2
  uuid: ^4.5.1
  
  # Validation
  email_validator: ^2.1.17
  
  # Utilities
  url_launcher: ^6.3.0
  
  # Animation
  #animated_text_kit: ^4.2.2
  #convex_bottom_bar: ^3.2.0
  #animated_bottom_navigation_bar: ^1.4.0
  google_nav_bar: ^5.0.7

  # Firebase
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.6.0
  firebase_storage: ^12.0.0
  image_picker: ^1.1.2
  google_sign_in: ^6.2.1
  firebase_messaging: ^15.1.0
  flutter_local_notifications: ^17.2.1
  dotted_border: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
flutter_launcher_icons:
  android: true
  ios: true
  adaptive_icon_background: "#000000"                      # hoặc ảnh: assets/icons/ic_bg.png
  adaptive_icon_foreground: "assets/icons/app_icon_v3.jpg"    # phần foreground
  image_path: "assets/icons/app_icon_v3.jpg"                  # vẫn giữ để iOS dùng
